import * as S3 from "./S3.generated";
import * as CloudFront from "./CloudFront.generated";
import * as Route53 from "./Route53.generated";
import * as ApiGateway from "./ApiGateway.generated";
import * as AutoScaling from "./AutoScaling.generated";
import * as CloudWatchLogs from "./CloudWatchLogs.generated";
import * as DynamoDB from "./DynamoDB.generated";
import * as EC2Networking from "./EC2-Networking.generated";
import * as ECSCluster from "./ECS-Cluster.generated";
import * as ECSServices from "./ECS-Services.generated";
import * as ECSTasks from "./ECS-Tasks.generated";
import * as ELB from "./ELB.generated";
import * as Lambda from "./Lambda.generated";
import * as RDS from "./RDS.generated";
import * as SNS from "./SNS.generated";
import * as SQS from "./SQS.generated";

// This file is autogenerated using infrascan-codegen. Do not manually edit this file.
const GLOBAL_SERVICE_SCANNERS = {
    "s3": [S3.performScan],
    "cloudfront": [CloudFront.performScan],
    "route-53": [Route53.performScan]
};
const REGIONAL_SERVICE_SCANNERS = {
    "api-gateway": [ApiGateway.performScan],
    "auto-scaling": [AutoScaling.performScan],
    "cloudwatch-logs": [CloudWatchLogs.performScan],
    "dynamodb": [DynamoDB.performScan],
    "ec2": [EC2Networking.performScan],
    "ecs": [ECSCluster.performScan, ECSServices.performScan, ECSTasks.performScan],
    "elastic-load-balancing-v2": [ELB.performScan],
    "lambda": [Lambda.performScan],
    "rds": [RDS.performScan],
    "sns": [SNS.performScan],
    "sqs": [SQS.performScan]
};

export { REGIONAL_SERVICE_SCANNERS, GLOBAL_SERVICE_SCANNERS };
