import { Project, SourceFile, VariableDeclarationKind } from "ts-morph";
import type { ScannerDefinition } from "./types";

function kebabCaseToCamelCase(val: string): string {
  const tokens = val.split("-");
  const capitalisedTokens = tokens
    .slice(1)
    .map((token) => token.charAt(0).toUpperCase() + token.slice(1));
  return [tokens[0], ...capitalisedTokens].join("");
}

function addServiceScannerImport(sourceFile: SourceFile, service: string) {
  sourceFile.addImportDeclaration({
    namespaceImport: kebabCaseToCamelCase(service),
    moduleSpecifier: `./${service}.generated`,
  });
}

function createScannerExportObject(services: ScannerDefinition[]) {
  const preparedServices = services.reduce(
    (scannersByService, currentService) => {
      if (scannersByService[currentService.service]) {
        scannersByService[currentService.service].push(currentService.key);
      } else {
        scannersByService[currentService.service] = [currentService.key];
      }
      return scannersByService;
    },
    {} as Record<string, string[]>
  );
  const keyValuePairs = Object.entries(preparedServices)
    .map(([serviceName, scanners]) => {
      const scannersFnList = scanners
        .map((clientKey) => `${kebabCaseToCamelCase(clientKey)}.performScan`)
        .join(", ");
      return `"${serviceName}": [${scannersFnList}]`;
    })
    .join(",\n");

  return `{\n${keyValuePairs}\n}`;
}

function declareScannerListAsConstant(
  sourceFile: SourceFile,
  services: ScannerDefinition[]
) {
  const globalServices = services.filter((service) => service.isGlobal);
  const globalScannersExport = createScannerExportObject(globalServices);
  const globalScannersVariable = "GLOBAL_SERVICE_SCANNERS";
  sourceFile.addVariableStatement({
    declarationKind: VariableDeclarationKind.Const,
    declarations: [
      {
        name: globalScannersVariable,
        initializer: globalScannersExport,
      },
    ],
  });

  const regionalServices = services.filter((service) => !service.isGlobal);
  const regionalScannersExport = createScannerExportObject(regionalServices);
  const regionalScannersVariable = "REGIONAL_SERVICE_SCANNERS";
  sourceFile.addVariableStatement({
    declarationKind: VariableDeclarationKind.Const,
    declarations: [
      {
        name: regionalScannersVariable,
        initializer: regionalScannersExport,
      },
    ],
  });

  sourceFile.addExportDeclaration({
    namedExports: [regionalScannersVariable, globalScannersVariable],
  });
}

export function generateEntrypoint(
  project: Project,
  basePath: string,
  services: ScannerDefinition[],
  verbose: boolean
) {
  const sourceFile = project.createSourceFile(
    `./${basePath}/index.generated.ts`
  );

  sourceFile.insertText(
    0,
    "// This file is autogenerated using infrascan-codegen. Do not manually edit this file.\n"
  );
  for (let service of services) {
    addServiceScannerImport(sourceFile, service.key);
  }
  // Create list of service modules imported
  declareScannerListAsConstant(sourceFile, services);

  sourceFile.formatText();
  if (verbose) {
    console.log(sourceFile.getFilePath());
    console.log(sourceFile.getText());
  }
  sourceFile.saveSync();
}
