name: Release Packages

on:
  release:
    types: [published]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs: 
  publish-cli:
    if: ${{ contains(github.ref,'@infrascan/cli') }}
    uses: ./.github/workflows/release.yml
    with:
      package: cli
      workspace: packages/cli
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-config:
    if: ${{ contains(github.ref, '@infrascan/config') }}
    uses: ./.github/workflows/release.yml
    with:
      package: config
      workspace: packages/config
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-fs-connector:
    if: ${{ contains(github.ref, '@infrascan/fs-connector') }}
    uses: ./.github/workflows/release.yml
    with:
      package: fs-connector
      workspace: packages/fs-connector
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-sdk:
    if: ${{ contains(github.ref, '@infrascan/sdk') }}
    uses: ./.github/workflows/release.yml
    with:
      package: sdk
      workspace: packages/sdk
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    