name: Release Packages

on:
  release:
    types: [published]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs: 
  find-release-candidate:
    runs-on: ubuntu-latest
    outputs:
      candidate_found: ${{ steps.find-candidate.outputs.release-candidate-found }}
      candidate_package: ${{ steps.find-candidate.outputs.candidate-package }}
      candidate_workspace: ${{ steps.find-candidate.outputs.candidate-workspace }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Prepare action
        run: |
          npm i -w internal/release-scanners
      - name: Find Candidate
        id: find-candidate
        uses: ./internal/release-scanners
        with:
          release-tag: ${{ github.ref }}
    
  publish-candidate:
    needs: [ find-release-candidate ]
    if: ${{ needs.find-release-candidate.outputs.candidate_found }}
    uses: ./.github/workflows/release.yml
    with:
      package: ${{ needs.find-release-candidate.outputs.candidate_package }}
      workspace: ${{ needs.find-release-candidate.outputs.candidate_workspace }}
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}