name: Release Packages

on:
  release:
    types: [published]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs: 
  find-release-candidate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Find Candidate
        id: find-candidate
        uses: ./internal/release-scanners
        with:
          release-tag: ${{ github.ref }}
      - name: Set output
        run: |
          echo "candidate_found=${{ steps.find-candidate.outputs.release-candidate-found }}" >> "$GITHUB_OUTPUT"
          echo "candidate_package=${{ steps.find-candidate.outputs.candidate-package }}" >> "$GITHUB_OUTPUT"
          echo "candidate_workspace=${{ steps.find-candidate.outputs.candidate-workspace }}" >> "$GITHUB_OUTPUT"
    
  publish-candidate:
    needs: [ find-release-candidate ]
    if: ${{ needs.find-release-candidate.outputs.candidate_found }}
    uses: ./.github/workflows/release.yml
    with:
      package: ${{ needs.find-release-candidate.outputs.candidate_package }}
      workspace: ${{ needs.find-release-candidate.outputs.candidate_workspace }}
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}